-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1
local title = {['BadgeID']=1,['BadgeLevel']=2,['EffectPath']=3}
local data = {
{ BadgeID = 1, BadgeLevel = 1, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile1' },
{ BadgeID = 1, BadgeLevel = 3, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile2' },
{ BadgeID = 1, BadgeLevel = 5, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile3' },
{ BadgeID = 2, BadgeLevel = 1, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile1' },
{ BadgeID = 2, BadgeLevel = 3, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile2' },
{ BadgeID = 2, BadgeLevel = 5, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile3' },
{ BadgeID = 3, BadgeLevel = 1, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile1' },
{ BadgeID = 3, BadgeLevel = 3, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile2' },
{ BadgeID = 3, BadgeLevel = 5, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile3' },
{ BadgeID = 4, BadgeLevel = 1, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile1' },
{ BadgeID = 4, BadgeLevel = 3, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile2' },
{ BadgeID = 4, BadgeLevel = 5, EffectPath = 'ui/UI_effect_beile/shengtangwenyao/shengtangwenyao_beile3' }
}

return {data, title}