-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1
local title = {['ID']=0,['Name']=1,['TextName']=2,['IconID']=3,['NumericalRate']=4,['ItemID']=5,['BuffID']=6,['SkillID']=7,['AttackParam']=8,['Vector3Test']=9,['Vector2Test']=10,['key']=11,['AwardList']=12,['Type']=13,['Pos']=14}
local data = {
{ ID = 100, Name = "黑猫警长", TextName = "黑猫警长，", IconID = 0, NumericalRate = 0.6, ItemID = 100, BuffID = {10}, SkillID = {{x=4,y=6}, {x=8,y=9}}, AttackParam = 1, Vector3Test = {{x=3,y=4,z=5}}, Vector2Test = {x=1,y=2}, key = 1, AwardList = {10, 3, 4}, Type = "Leader", Pos = {{X=100,Y=89},{X=20,Y=30}}},
{ ID = 101, Name = "葫芦\n娃", TextName = "", IconID = 0, NumericalRate = 0.8, ItemID = 100, BuffID = {3, 1}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 2, AwardList = {1, 3, 5}, Type = "Pig", Pos = {{X=100,Y=89},{X=20,Y=39}}},
{ ID = 102, Name = "舒\"克\"", TextName = "", IconID = 0, NumericalRate = 0.7, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 3, AwardList = {}, Type = "Hammer"},
{ ID = 103, Name = "贝\n塔", TextName = "", IconID = 0, NumericalRate = 0, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = "one", AwardList = {}, Type = "Monkey"},
{ ID = 104, Name = "邋遢大王", TextName = "", IconID = 0, NumericalRate = 1, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 5, AwardList = {}, Type = "Pig"}
}

return {data, title}