-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1
local title = {['BadgeID']=1,['Name']=2,['UnlockLevel']=3,['WearLevel']=4}
local data = {
{ 1,'勇武',200,10 },
{ 2,'睿智',260,12 },
{ 3,'坚韧',280,13 },
{ 4,'慷慨',300,14 }
}
return {data, title}