-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.1
local title = {['ID']=1,['Name']=2,['TextName']=3,['IconID']=4,['ItemID']=5,['BuffID']=6,['SkillID']=7,['AttackParam']=8,['Vector3Test']=9,['Vector2Test']=10,['key']=11,['AwardList']=12,['Type']=13,['Pos']=14,['PosSingle']=15,['SkillCache']=16,['ArrayEx']=17,['ArrayExFloat']=18,['IsRobot']=19}
local data = {
[0.1]={ ID = 100, Name = '黑猫警长', TextName = '黑猫警长，', IconID = 0, Rate = 0.1, ItemID = 100, BuffID = {10}, SkillID = {{x=4,y=6}, {x=8,y=9}}, AttackParam = 1, Vector3Test = {{x=3,y=4,z=5}}, Vector2Test = {x=1,y=2}, key = 1, AwardList = {10, 3, 4}, Type = 0, Pos = {{X=100,Y=89},{X=20,Y=30}}, PosSingle = {X=100,Y=89}, SkillCache = {0, 0.333}, ArrayEx = {{0, 1}, {2, 3}}, ArrayExFloat = {{0.1, 0.2, 0.3}, {0.4, 0.5, 0.6}}, IsRobot = true },
[0.5]={ ID = 101, Name = '葫芦\n娃', TextName = '', IconID = 0, Rate = 0.5, ItemID = 100, BuffID = {3, 1}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 2, AwardList = {1, 3, 5}, Type = 2, Pos = {{X=100,Y=89},{X=20,Y=39}}, PosSingle = {X=100,Y=20}, SkillCache = {0, 0.467}, ArrayEx = {}, ArrayExFloat = {}, IsRobot = false },
[0.3]={ ID = 102, Name = '舒\"克\"', TextName = '', IconID = 0, Rate = 0.3, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 3, AwardList = {}, Type = 3, Pos = {{}}, PosSingle = {X=100,Y=89}, SkillCache = {0, 0.533}, ArrayEx = {}, ArrayExFloat = {}, IsRobot = false },
[0.6]={ ID = 103, Name = '贝\n塔', TextName = '', IconID = 0, Rate = 0.6, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 'one', AwardList = {}, Type = 1, Pos = {{}}, PosSingle = {X=0,Y=0}, SkillCache = {0, 0.533}, ArrayEx = {}, ArrayExFloat = {}, IsRobot = false },
[0.7]={ ID = 104, Name = '邋遢大王', TextName = '', IconID = 0, Rate = 0.7, ItemID = 100, BuffID = {}, SkillID = {}, AttackParam = 0, Vector3Test = {}, Vector2Test = {x=0,y=0}, key = 5, AwardList = {}, Type = 2, Pos = {{}}, PosSingle = {X=0,Y=0}, SkillCache = {}, ArrayEx = {}, ArrayExFloat = {}, IsRobot = false }
}

return {data, title}